// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// Write a function that returns the sum of all the even-valued Fibonacci terms that are less or equal to
// the limit(integer)

function sumOfEvenFibonacciTerms (limit) {
  if (typeof limit !== 'number') throw Error('must be an number')
  // console.log ([...Array(limit).keys()])
  // var arrayA = [...Array(limit).keys()]
  // arrayA.map((e, index) => {
  //   console.log(arrayA[index + 1])
  //   return e + arrayA[index + 1]
  // })
  // console.log(arrayA)
  // [...Array(limit).keys()].forEach(e => {
  //   console.log(e);
  // })
  var sum
  return sum
}

module.exports = sumOfEvenFibonacciTerms
